on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Used to Github see all file into repo
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # in this step the github build the image, tagged it and push it to dockerhub
      - name: Build and push image
        run: |
          docker build -t estuda-app .
          docker tag estuda-app:latest ${{ vars.DOCKERHUB_USERNAME }}/estuda-app:latest
          docker push ${{ vars.DOCKERHUB_USERNAME }}/estuda-app:latest

      # initialing the terraform execution
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false 

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform -chdir=terraform plan -no-color -out=tfplan
        continue-on-error: true # Allow the workflow to continue even if plan fails

      - name: Terraform Apply
        run: terraform -chdir=terraform apply tfplan
