on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_NAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        run: |
          docker build -t estuda-app .
          docker tag estuda-app:latest ${{ vars.DOCKERHUB_NAME }}/estuda-app:latest
          docker push ${{ vars.DOCKERHUB_NAME }}/estuda-app:latest

      # - name: Login to Google Cloud Container Registry (GCR)
      #   uses: google/cloud-sdk@v4
      #   with:
      #     credentials: ${{ secrets.GITHUB_TOKEN }}
      #     project_id: your-project-id

      # - name: Execute Terraform script
      #   run: |
      #     terraform init -reconfigure \
      #       -working-directory=. \
      #       -input=false
      #     terraform apply -auto-approve
